### ISSUE TITLE
"no-duplicate-case": true

### ISSUE THREAD

**Issue by liangfeng1107** [aaronchenwei/tslint-config#20]
# [no-duplicate-case](https://eslint.org/docs/rules/no-duplicate-case)

set to:

```js
"no-duplicate-case": true
```

This rule disallows the programmer duplicate `case` clauses of `switch` statements.

```ts
// Bad
const a = 'A';
switch (a){
  case 'A':
    break;
  case 'B':
    break;
  case 'A':
    break;
  default:
    break;
}
```

```ts
// Good
const a = 'A';
switch (a){
  case 'A':
    break;
  case 'B':
    break;
  case 'C':
    break;
  default:
    break;
}
```

**Comment by aaronchenwei** [comment]
Sorry I need to revoke my previous comments. I suggest that we should not use `no-duplicate-case` from `tslint-eslint-rules`.

Instead,  we can use rule [`no-duplicate-switch-case`](https://palantir.github.io/tslint/rules/no-duplicate-switch-case/) from `tslint`.

**Comment by aaronchenwei** [comment]
#19

**Comment by aaronchenwei** [comment]
close this issue for now
