### ISSUE TITLE
no-control-regex

### ISSUE THREAD

**Issue by liangfeng1107** [aaronchenwei/tslint-config#23]
Should I add `no-control-regex` in this config?

In ESLint, `no-control-regex` is meaning:

**[Control characters are special, invisible characters in the ASCII range 0-31. These characters are rarely used in JavaScript strings so a regular expression containing these characters is most likely a mistake.](https://eslint.org/docs/rules/no-control-regex)**

So, if we set `"no-control-regex": true`, in our project:

```ts
// Bad
const reg1 = /\x1e/;
const reg2 = new RegExp("\x1e");
```

```ts
// Good
const reg1 = /\x30/;
const reg2 = new RegExp("\x30");
```

**Comment by aaronchenwei** [comment]
I voted NO for this rule. There is no strong use case for now. We could revisit it later.

**Comment by aaronchenwei** [comment]
ref #19
