### ISSUE TITLE
"no-invalid-regexp": true

### ISSUE THREAD

**Issue by liangfeng1107** [aaronchenwei/tslint-config#26]
An invalid pattern in a regular expression literal is a `SyntaxError` when the code is parsed, but an invalid string in `RegExp` constructors throws a `SyntaxError` only when the code is executed.

``` ts
// Bad
RegExp('[')

RegExp('.', 'z')

new RegExp('\\')
```

``` ts
// Good
RegExp('.')

new RegExp

this.RegExp('[')
```

Although I think this rule is needed, I am still confused about these examples. Why `RegExp('[')` is bad but `this.RegExp('[')` is good?

**Comment by aaronchenwei** [comment]
`this.RegExp('[')` is a regular function call not RegExp...

**Comment by liangfeng1107** [comment]
We currently do not set rules for regular.
