### ISSUE TITLE
"no-unexpected-multiline": true

### ISSUE THREAD

**Issue by liangfeng1107** [aaronchenwei/tslint-config#31]
In the exceptions where a newline does not end a statement, a typing mistake to omit a semicolon causes two unrelated consecutive lines to be interpreted as one expression. Especially for a coding style without semicolons, readers might overlook the mistake. Although syntactically correct, the code might throw exceptions when it is executed.

``` ts
// Bad
const foo = bar
(1 || 2).baz();

const hello = 'world'
[1, 2, 3].forEach(addNumber);

let x = function() {}
`hello`

let x = function() {}
x
`hello`

let x = foo
/regex/g.test(bar)
```

``` ts
// Good
const foo = bar;
(1 || 2).baz();

const foo = bar
;(1 || 2).baz()

const hello = 'world';
[1, 2, 3].forEach(addNumber);

const hello = 'world'
void [1, 2, 3].forEach(addNumber);

let x = function() {};
`hello`

let tag = function() {}
tag `hello`
```

**Comment by aaronchenwei** [comment]
It is **NOT** necessary to enable this `no-unexpected-multiline` as `prettier` would handle such multiple line styles.

**Comment by aaronchenwei** [comment]
#19

**Comment by aaronchenwei** [comment]
close this issue for now
