### ISSUE TITLE
"file-name-casing": [true, "pascal-case"]

### ISSUE THREAD

**Issue by liangfeng1107** [aaronchenwei/tslint-config#47]
Enforces a consistent file naming convention.

# Config
One of the following arguments must be provided:

- camel-case: File names must be camel-cased: `fileName.ts`.
- pascal-case: File names must be Pascal-cased: `FileName.ts`.
- kebab-case: File names must be kebab-cased: `file-name.ts`.

**Comment by liangfeng1107** [comment]
ref #17

**Comment by aaronchenwei** [comment]
close it for now. 

we can re-open it later.
