### ISSUE TITLE
"newline-before-return": true

### ISSUE THREAD

**Issue by liangfeng1107** [aaronchenwei/tslint-config#48]
There is no hard and fast rule about whether empty lines should precede `return` statements in JavaScript. However, clearly delineating where a function is returning can greatly increase the readability and clarity of the code. For example:

``` ts
function foo(bar) {
  const baz = 'baz';
  if (!bar) {
    bar = baz;
    return bar;
  }
  return bar;
}
```

Adding newlines visibly separates the return statements from the previous lines, making it clear where the function exits and what value it returns:

``` ts
function foo(bar) {
  const baz = 'baz';

  if (!bar) {
    bar = baz;

    return bar;
  }

  return bar;
}
```

**Comment by liangfeng1107** [comment]
ref #17

**Comment by aaronchenwei** [comment]
let's include it in v0.5

#82
