### ISSUE TITLE
"newline-per-chained-call": true

### ISSUE THREAD

**Issue by liangfeng1107** [aaronchenwei/tslint-config#49]
# "newline-per-chained-call": true

Chained method calls on a single line without line breaks are harder to read, so some developers place a newline character after each method call in the chain to make it more readable and easy to maintain.

Let’s look at the following perfectly valid (but single line) code.

```ts
d3.select('body')
  .selectAll('p')
  .data([4, 8, 15, 16, 23, 42])
  .enter()
  .append('p')
  .text(function(d) {
    return "I'm number " + d + '!';
  });
```

However, with appropriate new lines, it becomes easy to read and understand. Look at the same code written below with line breaks after each call.

```ts
d3.select('body')
  .selectAll('p')
  .data([4, 8, 15, 16, 23, 42])
  .enter()
  .append('p')
  .text(function(d) {
    return "I'm number " + d + '!';
  });
```

**Comment by liangfeng1107** [comment]
ref #17

**Comment by aaronchenwei** [comment]
let's include it in v0.5

#82

**Comment by aaronchenwei** [comment]
this rule conflicts with `tslint-config-prettier`. 

we don't need to enable it.
