### ISSUE TITLE
"no-duplicate-imports": true

### ISSUE THREAD

**Issue by liangfeng1107** [aaronchenwei/tslint-config#52]
# "no-duplicate-imports": true

Using a single `import` statement per module will make the code clearer because you can see everything being imported from that `module` on one line.

```ts
// Bad
import { merge } from 'module';
import something from 'another-module';
import { find } from 'module';
```

```ts
// Good
import { merge, find } from 'module';
import something from 'another-module';
```

**Comment by aaronchenwei** [comment]
[Rule: no-duplicate-imports](https://palantir.github.io/tslint/rules/no-duplicate-imports/)

#82
