### ISSUE TITLE
"no-object-literal-type-assertion": true

### ISSUE THREAD

**Issue by liangfeng1107** [aaronchenwei/tslint-config#56]
# "no-object-literal-type-assertion": true

Always prefer `const x: T = { ... };` to `const x = { ... } as T;`. The type assertion in the latter case is either unnecessary or hides an error. The compiler will warn for excess properties with this syntax, but not missing required fields. For example: `const x: { foo: number } = {}` will fail to compile, but `const x = {} as { foo: number }` will succeed.

```ts
// Bad
const x = { ... } as T;
```

```ts
// Good
const x: T = { ... };
```

**Comment by liangfeng1107** [comment]
ref #17

**Comment by aaronchenwei** [comment]
[Rule: no-object-literal-type-assertion](https://palantir.github.io/tslint/rules/no-object-literal-type-assertion/)

#82
