### ISSUE TITLE
"no-parameter-reassignment": true

### ISSUE THREAD

**Issue by liangfeng1107** [aaronchenwei/tslint-config#61]
# "no-parameter-reassignment": true

Assignment to variables declared as function parameters can be misleading and lead to confusing behavior, as modifying function parameters will also mutate the arguments object. Often, assignment to function parameters is unintended and indicative of a mistake or programmer error.

```ts
// Bad
foo = bar => {
  bar = 13;
};

foo = bar => {
  bar++;
};
```

```ts
// Good
foo = bar => {
  const baz = bar;
};
```

**Comment by aaronchenwei** [comment]
[Rule: no-parameter-reassignment](https://palantir.github.io/tslint/rules/no-parameter-reassignment/)

#82

**Comment by aaronchenwei** [comment]
more information about this rule

- https://stackoverflow.com/questions/35637770/how-to-avoid-no-param-reassign-when-setting-a-property-on-a-dom-object
- https://spin.atomicobject.com/2011/04/10/javascript-don-t-reassign-your-function-arguments/
