### ISSUE TITLE
"no-for-in-array": true

### ISSUE THREAD

**Issue by liangfeng1107** [aaronchenwei/tslint-config#62]
# "no-for-in-array": true

Disallows iterating over an array with a for-in loop.

A for-in loop (for (var k in o)) iterates over the properties of an Object.

While it is legal to use for-in loops with array types, it is not common. for-in will iterate over the indices of the array as strings, omitting any “holes” in the array.

More common is to use for-of, which iterates over the values of an array. If you want to iterate over the indices, alternatives include:

array.forEach((value, index) => { … }); for (const [index, value] of array.entries()) { … } for (let i = 0; i < array.length; i++) { … }

**Comment by liangfeng1107** [comment]
Need replace `no-for-in` in `tslint-microsoft-contrib`

**Comment by aaronchenwei** [comment]
[Rule: no-for-in-array](https://palantir.github.io/tslint/rules/no-for-in-array/)

We can include this in v0.5.

#82

**Comment by aaronchenwei** [comment]
[stackoverflow](https://stackoverflow.com/questions/500504/why-is-using-for-in-with-array-iteration-a-bad-idea)

```js
var a = []; // Create a new empty array.
a[5] = 5;   // Perfectly legal JavaScript that resizes the array.

for (var i = 0; i < a.length; i++) {
    // Iterate over numeric indexes from 0 to 5, as everyone expects.
    console.log(a[i]);
}

/* Will display:
   undefined
   undefined
   undefined
   undefined
   undefined
   5
*/
```

```js
var a = [];
a[5] = 5;
for (var x in a) {
    // Shows only the explicitly set index of "5", and ignores 0-4
    console.log(x);
}

/* Will display:
   5
*/
```

another example
```js
// Somewhere deep in your JavaScript library...
Array.prototype.foo = 1;

// Now you have no idea what the below code will do.
var a = [1, 2, 3, 4, 5];
for (var x in a){
    // Now foo is a part of EVERY array and 
    // will show up here as a value of 'x'.
    console.log(x);
}

/* Will display:
   0
   1
   2
   3
   4
   foo
*/
```
