### ISSUE TITLE
review rule - no-inferrable-types

### ISSUE THREAD

**Issue by aaronchenwei** [aaronchenwei/tslint-config#92]
[doc](https://palantir.github.io/tslint/rules/no-inferrable-types/)

**Comment by liangfeng1107** [comment]
In [doc](https://github.com/bradzacher/eslint-plugin-typescript/blob/master/docs/rules/no-inferrable-types.md), we can use it. But I think it should be set: `"no-inferrable-types": [true, "ignore-params", "ignore-properties"]`

```ts
fn = (a: number = 5, b: number | string = 6) => {};
```

is not same to:

```ts
fn = (a: number, b: number | string) => {};
```

Or

```ts
fn = (a = 5, b = 6) => {};
```

**Comment by aaronchenwei** [comment]
After reading this [issue thread](https://github.com/palantir/tslint/issues/711), I don't think we would like to introduce this rule for now.

**Comment by aaronchenwei** [comment]
Close this issue for now. Please reopen if you have any comments.
