### ISSUE TITLE
review rule - prefer-template

### ISSUE THREAD

**Issue by aaronchenwei** [aaronchenwei/tslint-config#94]
in v0.6.0, we are using 

```js
    'prefer-template': [true, 'allow-single-concat'],
```

[tslint doc](https://palantir.github.io/tslint/rules/prefer-template/)

propose to change to 

```js
    'prefer-template': true,
```

**Comment by aaronchenwei** [comment]
https://medium.com/front-end-hacking/es6-cool-stuffs-a-new-js-string-with-template-literals-c23a8af11b2

**Comment by aaronchenwei** [comment]
if not considering JS performance, which way do you think is more readable?

```js
const a = 'abc'; 
const b = '123'; 

return a + b;

// vs

const a = 'abc'; 
const b = '123'; 

return `${a}${b}`;
```

**Comment by KarenWhoo** [comment]
There is one thing that we should notice when we use template literal
```js
const htmlTemplate =
    `<h2>Weather condition</h2>
     <p>The weather today will be cloudy</p>`
```

 me will thought that the variable will output the following result

```js

<h2>Weather condition</h2>
<p>The weather today will be cloudy</p>

```
But the result unfortunately will be:

```js
<h2>Weather condition</h2>
     <p>The weather today will be cloudy</p>

```

this is because in the template literal all characters are significant so leading whitespaces on a new row are not ignored.

**Comment by liangfeng1107** [comment]
I think `return a + b;` is more readable. But in other example, it will be:

```ts
const a = 'abc';
const b = '123';
const c = a + b;
const d = c + a;
...

// vs

const a = 'abc';
const b = '123';
const c = `${a}${b}`;
const d = `${a}${b}${a}`;
...
```

The second will be more readable.

**Comment by KarenWhoo** [comment]
http://usefulangle.com/post/16/performance-of-template-literals-vs-string-concatenation-in-multiline-strings

Abourt JS performance, this article also says that there is no performance gain in using template literals.

**Comment by KarenWhoo** [comment]
> 
> 
> if not considering JS performance, which way do you think is more readable?
> 
> ```js
> const a = 'abc'; 
> const b = '123'; 
> 
> return a + b;
> 
> // vs
> 
> const a = 'abc'; 
> const b = '123'; 
> 
> return `${a}${b}`;
> ```

I prefer a+b

**Comment by aaronchenwei** [comment]
airbnb https://github.com/airbnb/javascript#es6-template-literals
