### ISSUE TITLE
"no-arg": true

### ISSUE THREAD

**Issue by liangfeng1107** [aaronchenwei/tslint-config#97]
# "no-arg": true

Disallows use of arguments.callee.

Using arguments.callee makes various performance optimizations impossible. See [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments/callee) for more details on why to avoid arguments.callee.

**Comment by aaronchenwei** [comment]
it is `true` in our tslint-config
